In [81]:
#methods of numpy
#IF-5-K
#Yash Ramesh Jadhav
import numpy as np

In [82]:
ar1=np.array([[25,26,27],[35,36,37]])
print("Shape: ",ar1.shape)

Shape:  (2, 3)


In [83]:
print("Size: ",ar1.size)

Size:  6


In [84]:
print("Dimensions: ",ar1.ndim)

Dimensions:  2


In [85]:
print("Data Type: ",ar1.dtype)

Data Type:  int64


In [86]:
ar2=np.array([[1,2,3],[4,5,6]])
print("Original Array: \n",ar2)
print(ar2.shape)
print("Reshaped array: \n",ar2.reshape(3,2))
print("Flatenned: ",ar2.flatten())

Original Array: 
 [[1 2 3]
 [4 5 6]]
(2, 3)
Reshaped array: 
 [[1 2]
 [3 4]
 [5 6]]
Flatenned:  [1 2 3 4 5 6]


In [87]:
ar3=np.array([[30,20,50],[60,70,40],[80,90,100]])
print("Original Array no. 3:\n",ar3)

Original Array no. 3:
 [[ 30  20  50]
 [ 60  70  40]
 [ 80  90 100]]


In [88]:
np.all(ar3)
np.any(ar3)

np.True_

In [89]:
np.max(ar3,axis=0)

array([ 80,  90, 100])

In [90]:
np.min(ar3,axis=1)

array([20, 40, 80])

In [91]:
np.sum(ar3)

np.int64(540)

In [92]:
np.prod(ar3,axis=0)

array([144000, 126000, 200000])

In [93]:
np.median(ar3)

np.float64(60.0)

In [94]:
np.percentile(ar3,90)

np.float64(92.0)

In [95]:
np.argmin(ar3)

np.int64(1)

In [96]:
np.argmax(ar3)

np.int64(8)

In [97]:
#np.unique(ar3)

In [98]:
np.diff(ar3)

array([[-10,  30],
       [ 10, -30],
       [ 10,  10]])

In [99]:
np.cumsum(ar3)

array([ 30,  50, 100, 160, 230, 270, 350, 440, 540])